# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 068e0925e54932fe100e076ac4bcb6a641f692cb15c9fda417fa6e76a5b8b0155dd33cecf9e9d1b95134d12e7b460dee05ce51548a4ab086551d5e22c1bdc5af

test:
  secret_key_base: 7dfa45c14e2220eb3fe3f4c60ae9285e760b68970d3becd28603bf20edf5136ee9f90af1272ebb737627d12f0b32c5f21a6f34c93437f125c5bc97890f42ac29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
